{"uuid": "7c0d564e-f436-4897-8251-dd3197627f31", "children": ["7bad2165-b102-4636-85d3-9985abb1e956"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "NameError: name 'url' is not defined\n", "trace": "  File \"c:\\PYTHON-PROJECTS\\env\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"c:\\PYTHON-PROJECTS\\env\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"c:\\PYTHON-PROJECTS\\env\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\PYTHON-PROJECTS\\env\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1149, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\PYTHON-PROJECTS\\env\\Lib\\site-packages\\_pytest\\fixtures.py\", line 916, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"c:\\PYTHON-PROJECTS\\tests\\frontend_tests\\conftest.py\", line 28, in browser\n    driver.get(url=url)\n                  ^^^\n"}, "start": 1706428404553, "stop": 1706428406279}], "start": 1706428404553, "stop": 1706428406404}